import { NextRequest, NextResponse } from 'next/server'
import withAuth from './middlewares/withAuth'

export function mainMiddleware(request: NextRequest) {
    return NextResponse.next()
}

const protectedPaths = [
    '/profil',
    '/manajemen-data',
    '/manajemen-data/pengguna',
    '/manajemen-data/area',
    '/manajemen-data/status',
    '/manajemen-institusi',
    '/manajemen-institusi/institusi',
    '/manajemen-institusi/jabatan',
    '/manajemen-institusi/sosial-media',
    '/manajemen-sistem',
    '/manajemen-sistem/role',
    '/manajemen-sistem/permission',
    '/manajemen-sistem/api-key',
    '/manajemen-pembelajaran',
    '/manajemen-pembelajaran/program-studi',
    '/manajemen-pembelajaran/mata-kuliah',
    '/manajemen-pembelajaran/capaian',
    '/manajemen-pembelajaran/jenis-dokumen',
    '/asesor',
    '/asesor/penunjukan-asesor',
    '/asesor/sk-rektor',
    '/kelengkapan-informasi',
    '/kelengkapan-informasi/institusi-lama',
    '/kelengkapan-informasi/pendidikan',
    '/kelengkapan-informasi/pekerjaan',
    '/kelengkapan-informasi/organisasi-profesi',
    '/kelengkapan-informasi/orang-tua',
    '/kelengkapan-informasi/pelatihan-profesional',
    '/kelengkapan-informasi/konferensi-seminar',
    '/kelengkapan-informasi/kejuaraan-piagam',
    '/evaluasi-mandiri',
    '/upload-dokumen',
    '/asessment',
    '/asessment/asessmen-mahasiswa',
    '/asessment/sanggahan-mahasiswa',
    '/asessment/hasil-asessmen',
    '/asessment/sk-rektor',
    '/proses-bisnis-rpl',
    '/buku-petunjuk',
    '/dukungan',
    '/question',
    '/notifikasi',
]

export default withAuth(mainMiddleware, protectedPaths)

export const config = {
    matcher: [
        '/profil/:path*',
        '/manajemen-data/:path*',
        '/manajemen-data/pengguna/:path*',
        '/manajemen-data/area/:path*',
        '/manajemen-data/status/:path*',
        '/manajemen-institusi/:path*',
        '/manajemen-institusi/institusi/:path*',
        '/manajemen-institusi/jabatan/:path*',
        '/manajemen-institusi/sosial-media/:path*',
        '/manajemen-sistem/:path*',
        '/manajemen-sistem/role/:path*',
        '/manajemen-sistem/permission/:path*',
        '/manajemen-sistem/api-key/:path*',
        '/manajemen-pembelajaran/:path*',
        '/manajemen-pembelajaran/program-studi/:path*',
        '/manajemen-pembelajaran/mata-kuliah/:path*',
        '/manajemen-pembelajaran/capaian/:path*',
        '/manajemen-pembelajaran/jenis-dokumen/:path*',
        '/asesor/:path*',
        '/asesor/penunjukan-asesor/:path*',
        '/asesor/sk-rektor/:path*',
        '/kelengkapan-informasi/:path*',
        '/kelengkapan-informasi/institusi-lama/:path*',
        '/kelengkapan-informasi/pendidikan/:path*',
        '/kelengkapan-informasi/pekerjaan/:path*',
        '/kelengkapan-informasi/organisasi-profesi/:path*',
        '/kelengkapan-informasi/orang-tua/:path*',
        '/kelengkapan-informasi/pelatihan-profesional/:path*',
        '/kelengkapan-informasi/konferensi-seminar/:path*',
        '/kelengkapan-informasi/kejuaraan-piagam/:path*',
        '/evaluasi-mandiri/:path*',
        '/upload-dokumen/:path*',
        '/asessment/:path*',
        '/asessment/asessmen-mahasiswa/:path*',
        '/asessment/sanggahan-mahasiswa/:path*',
        '/asessment/hasil-asessmen/:path*',
        '/asessment/sk-rektor/:path*',
        '/proses-bisnis-rpl/:path*',
        '/buku-petunjuk/:path*',
        '/dukungan/:path*',
        '/question/:path*',
        '/notifikasi/:path*',
    ],
}
